#!/usr/bin/node

// Import the 'request' module
const request = require('request');

// Get the URL from the command-line arguments
const url = process.argv[2];

if (!url) {
  console.error('Error: URL not specified.');
  process.exit(1);
}

// Make a GET request to the specified URL
request(url, (error, response) => {
  if (error) {
    console.error('Error:', error);
    process.exit(1);
  }
  console.log('code:', response.statusCode);
});

